apiVersion: v1
kind: Service
metadata:
  name: alertmanager
  namespace: monitoring-demo
spec:
  type: LoadBalancer
  selector:
    app: alertmanager
  ports:
    - name: http
      port: 9093
      targetPort: 9093
