apiVersion: apps/v1
kind: Deployment
metadata:
  name: karma
  namespace: monitoring-demo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: karma
  template:
    metadata:
      labels:
        app: karma
    spec:
      containers:
        - name: karma
          image: ghcr.io/prymitive/karma:v0.120
          ports:
            - containerPort: 8081
          env:
            - name: ALERTMANAGER_URI
              value: "http://alertmanager:9093"
            - name: ALERTMANAGER_INTERVAL
              value: "10s"
            - name: PORT
              value: "8081"
          resources:
            requests:
              cpu: 50m
              memory: 64Mi
            limits:
              cpu: 100m
              memory: 128Mi
