apiVersion: v1
kind: Service
metadata:
  name: karma
  namespace: monitoring-demo
spec:
  type: LoadBalancer
  selector:
    app: karma
  ports:
    - name: http
      port: 8081
      targetPort: 8081
