apiVersion: v1
kind: Service
metadata:
  name: prometheus
  namespace: monitoring-demo
spec:
  type: LoadBalancer
  selector:
    app: prometheus
  ports:
    - name: http
      port: 9090
      targetPort: 9090
    - name: pyrra-api
      port: 9444
      targetPort: 9444
