apiVersion: v1
kind: Service
metadata:
  name: otel-watcher
  namespace: monitoring-demo
spec:
  selector:
    app: otel-watcher
  ports:
    - name: otlp-http
      port: 8090
      targetPort: 8090
