apiVersion: v1
kind: ConfigMap
metadata:
  name: otel-watcher-config
  namespace: monitoring-demo
data:
  RESOURCE_API_URL: "http://10.128.11.196:8000"
  AGENT_NAME: "otel-watcher"
  AGENT_TOKEN: "123"
  SCRAPE_INTERVAL: "30"
  SCRAPE_TARGETS: "fastapi-app:8000,flask-app:9464,otel-collector:8889"
