OTLP_TRACES_MAPPING = {
    "id": "otel-traces-mapper-v1",
    "name": "OpenTelemetry Traces Mapper v1.0",
    "source_type": "opentelemetry-traces",
    "version": "1.0.0",
    "description": "Maps OTLP traces to Service/Database/Table/ExternalAPI/Library nodes",
    "edge_preset_id": "default",
    "field_mappings": [
        {
            "id": "svc-id",
            "source_path": "resourceSpans[0].resource.attributes[?key=='service.name'].value.stringValue | [0]",
            "target_field": "id",
            "target_node_type": "Service",
            "transform_type": "template",
            "transform_config": {"template": "urn:service:{value}"},
        },
        {
            "id": "svc-name",
            "source_path": "resourceSpans[0].resource.attributes[?key=='service.name'].value.stringValue | [0]",
            "target_field": "name",
            "target_node_type": "Service",
        },
        {
            "id": "svc-peer",
            "source_path": "resourceSpans[0].scopeSpans[0].spans[0].attributes[?key=='peer.service'].value.stringValue | [0]",
            "target_field": "calls_services",
            "target_node_type": "Service",
            "description": "For calls edge to another Service",
        },
        {
            "id": "svc-version",
            "source_path": "resourceSpans[0].scopeSpans[0].spans[0].attributes[?key=='service.version'].value.stringValue | [0]",
            "target_field": "version",
            "target_node_type": "Service",
        },
        {
            "id": "svc-env",
            "source_path": "resourceSpans[0].scopeSpans[0].spans[0].attributes[?key=='deployment.environment'].value.stringValue | [0]",
            "target_field": "environment",
            "target_node_type": "Service",
        },
        {
            "id": "extapi-id",
            "source_path": "resourceSpans[0].scopeSpans[0].spans[0].attributes[?key=='external_api'].value.stringValue | [0]",
            "target_field": "id",
            "target_node_type": "ExternalAPI",
            "transform_type": "template",
            "transform_config": {"template": "urn:externalapi:{value}"},
        },
        {
            "id": "extapi-name",
            "source_path": "resourceSpans[0].scopeSpans[0].spans[0].attributes[?key=='external_api'].value.stringValue | [0]",
            "target_field": "name",
            "target_node_type": "ExternalAPI",
        },
        {
            "id": "svc-external-apis",
            "source_path": "resourceSpans[0].scopeSpans[0].spans[0].attributes[?key=='external_api'].value.stringValue | [0]",
            "target_field": "external_apis",
            "target_node_type": "Service",
            "description": "For calls edge to ExternalAPI",
        },
        {
            "id": "db-id",
            "source_path": "resourceSpans[0].scopeSpans[0].spans[0].attributes[?key=='db.name'].value.stringValue | [0]",
            "target_field": "id",
            "target_node_type": "Database",
            "transform_type": "template",
            "transform_config": {"template": "urn:database:{value}"},
        },
        {
            "id": "db-name",
            "source_path": "resourceSpans[0].scopeSpans[0].spans[0].attributes[?key=='db.name'].value.stringValue | [0]",
            "target_field": "name",
            "target_node_type": "Database",
        },
        {
            "id": "db-system",
            "source_path": "resourceSpans[0].scopeSpans[0].spans[0].attributes[?key=='db.system'].value.stringValue | [0]",
            "target_field": "engine",
            "target_node_type": "Database",
        },
        {
            "id": "svc-reads-db",
            "source_path": "resourceSpans[0].scopeSpans[0].spans[0].attributes[?key=='db.name'].value.stringValue | [0]",
            "target_field": "reads_databases",
            "target_node_type": "Service",
            "description": "For reads edge to Database",
        },
        {
            "id": "svc-writes-db",
            "source_path": "resourceSpans[0].scopeSpans[0].spans[0].attributes[?key=='db.name'].value.stringValue | [0]",
            "target_field": "writes_databases",
            "target_node_type": "Service",
            "description": "For writes edge to Database",
        },
        {
            "id": "table-id",
            "source_path": "resourceSpans[0].scopeSpans[0].spans[0].attributes[?key=='db.table'].value.stringValue | [0]",
            "target_field": "id",
            "target_node_type": "Table",
            "transform_type": "template",
            "transform_config": {"template": "urn:table:{value}"},
        },
        {
            "id": "table-name",
            "source_path": "resourceSpans[0].scopeSpans[0].spans[0].attributes[?key=='db.table'].value.stringValue | [0]",
            "target_field": "name",
            "target_node_type": "Table",
        },
        {
            "id": "svc-reads-table",
            "source_path": "resourceSpans[0].scopeSpans[0].spans[0].attributes[?key=='db.table'].value.stringValue | [0]",
            "target_field": "reads_tables",
            "target_node_type": "Service",
        },
        {
            "id": "svc-writes-table",
            "source_path": "resourceSpans[0].scopeSpans[0].spans[0].attributes[?key=='db.table'].value.stringValue | [0]",
            "target_field": "writes_tables",
            "target_node_type": "Service",
        },
        {
            "id": "lib-id",
            "source_path": "resourceSpans[0].resource.attributes[?key=='telemetry.sdk.name'].value.stringValue | [0]",
            "target_field": "id",
            "target_node_type": "Library",
            "transform_type": "template",
            "transform_config": {"template": "urn:library:{value}"},
        },
        {
            "id": "lib-name",
            "source_path": "resourceSpans[0].resource.attributes[?key=='telemetry.sdk.name'].value.stringValue | [0]",
            "target_field": "name",
            "target_node_type": "Library",
        },
        {
            "id": "lib-language",
            "source_path": "resourceSpans[0].resource.attributes[?key=='telemetry.sdk.language'].value.stringValue | [0]",
            "target_field": "language",
            "target_node_type": "Library",
            "default_value": "unknown",
        },
        {
            "id": "svc-libraries",
            "source_path": "resourceSpans[0].resource.attributes[?key=='telemetry.sdk.name'].value.stringValue | [0]",
            "target_field": "libraries",
            "target_node_type": "Service",
            "description": "For dependson edge to Library",
        },
        {
            "id": "svc-team",
            "source_path": "resourceSpans[0].scopeSpans[0].spans[0].attributes[?key=='team'].value.stringValue | [0]",
            "target_field": "team",
            "target_node_type": "Service",
            "description": "For ownedby edge to TeamOwner",
        },
        {
            "id": "svc-auth-secret",
            "source_path": "resourceSpans[0].scopeSpans[0].spans[0].attributes[?key=='auth_secret'].value.stringValue | [0]",
            "target_field": "auth_secret",
            "target_node_type": "Service",
            "description": "For authenticatesvia edge to SecretConfig",
        },
        {
            "id": "svc-rate-limit",
            "source_path": "resourceSpans[0].scopeSpans[0].spans[0].attributes[?key=='rate_limit_config'].value.stringValue | [0]",
            "target_field": "rate_limit_config",
            "target_node_type": "Service",
            "description": "For ratelimitedby edge to SecretConfig",
        },
        {
            "id": "secret-id",
            "source_path": "resourceSpans[0].scopeSpans[0].spans[0].attributes[?key=='auth_secret'].value.stringValue | [0]",
            "target_field": "id",
            "target_node_type": "SecretConfig",
            "transform_type": "template",
            "transform_config": {"template": "urn:secretconfig:{value}"},
        },
        {
            "id": "secret-name",
            "source_path": "resourceSpans[0].scopeSpans[0].spans[0].attributes[?key=='auth_secret'].value.stringValue | [0]",
            "target_field": "name",
            "target_node_type": "SecretConfig",
        },
        {
            "id": "svc-failover",
            "source_path": "resourceSpans[0].scopeSpans[0].spans[0].attributes[?key=='failover_service'].value.stringValue | [0]",
            "target_field": "failover_service",
            "target_node_type": "Service",
            "description": "For fails_over_to edge to Service",
        },
        {
            "id": "team-id",
            "source_path": "resourceSpans[0].scopeSpans[0].spans[0].attributes[?key=='team'].value.stringValue | [0]",
            "target_field": "id",
            "target_node_type": "TeamOwner",
            "transform_type": "template",
            "transform_config": {"template": "urn:teamowner:{value}"},
        },
        {
            "id": "team-name",
            "source_path": "resourceSpans[0].scopeSpans[0].spans[0].attributes[?key=='team'].value.stringValue | [0]",
            "target_field": "name",
            "target_node_type": "TeamOwner",
        },
        {
            "id": "svc-reads-cache",
            "source_path": "resourceSpans[0].scopeSpans[0].spans[0].attributes[?key=='cache.name'].value.stringValue | [0]",
            "target_field": "reads_caches",
            "target_node_type": "Service",
            "description": "For reads edge to Cache",
        },
        {
            "id": "cache-id",
            "source_path": "resourceSpans[0].scopeSpans[0].spans[0].attributes[?key=='cache.name'].value.stringValue | [0]",
            "target_field": "id",
            "target_node_type": "Cache",
            "transform_type": "template",
            "transform_config": {"template": "urn:cache:{value}"},
        },
        {
            "id": "cache-name",
            "source_path": "resourceSpans[0].scopeSpans[0].spans[0].attributes[?key=='cache.name'].value.stringValue | [0]",
            "target_field": "name",
            "target_node_type": "Cache",
        },
        {
            "id": "queue-id",
            "source_path": "resourceSpans[0].scopeSpans[0].spans[0].attributes[?key=='messaging.destination'].value.stringValue | [0]",
            "target_field": "id",
            "target_node_type": "QueueTopic",
            "transform_type": "template",
            "transform_config": {"template": "urn:queuetopic:{value}"},
        },
        {
            "id": "queue-name",
            "source_path": "resourceSpans[0].scopeSpans[0].spans[0].attributes[?key=='messaging.destination'].value.stringValue | [0]",
            "target_field": "name",
            "target_node_type": "QueueTopic",
        },
        {
            "id": "svc-publishes-queue",
            "source_path": "resourceSpans[0].scopeSpans[0].spans[0].attributes[?key=='messaging.publishes_to'].value.stringValue | [0]",
            "target_field": "publishes_to",
            "target_node_type": "Service",
            "description": "For publishesto edge to QueueTopic",
        },
        {
            "id": "svc-consumes-queue",
            "source_path": "resourceSpans[0].scopeSpans[0].spans[0].attributes[?key=='messaging.consumes_from'].value.stringValue | [0]",
            "target_field": "consumes_from",
            "target_node_type": "Service",
            "description": "For consumesfrom edge to QueueTopic",
        },
    ],
    "conditional_rules": [
        {
            "id": "cr-external-api",
            "condition": "resourceSpans[0].scopeSpans[0].spans[0].attributes[?key=='external_api'] | [0] != `null`",
            "target_node_type": "ExternalAPI",
            "priority": 50,
        },
        {
            "id": "cr-database",
            "condition": "resourceSpans[0].scopeSpans[0].spans[0].attributes[?key=='db.system'] | [0] != `null`",
            "target_node_type": "Database",
            "priority": 40,
        },
        {
            "id": "cr-table",
            "condition": "resourceSpans[0].scopeSpans[0].spans[0].attributes[?key=='db.table'] | [0] != `null`",
            "target_node_type": "Table",
            "priority": 35,
        },
        {
            "id": "cr-library",
            "condition": "resourceSpans[0].resource.attributes[?key=='telemetry.sdk.name'] | [0] != `null`",
            "target_node_type": "Library",
            "priority": 30,
        },
        {
            "id": "cr-cache",
            "condition": "resourceSpans[0].scopeSpans[0].spans[0].attributes[?key=='cache.name'] | [0] != `null`",
            "target_node_type": "Cache",
            "priority": 25,
        },
        {
            "id": "cr-secret",
            "condition": "resourceSpans[0].scopeSpans[0].spans[0].attributes[?key=='auth_secret'] | [0] != `null`",
            "target_node_type": "SecretConfig",
            "priority": 22,
        },
        {
            "id": "cr-queue",
            "condition": "resourceSpans[0].scopeSpans[0].spans[0].attributes[?key=='messaging.destination'] | [0] != `null`",
            "target_node_type": "QueueTopic",
            "priority": 20,
        },
        {
            "id": "cr-team",
            "condition": "resourceSpans[0].scopeSpans[0].spans[0].attributes[?key=='team'] | [0] != `null`",
            "target_node_type": "TeamOwner",
            "priority": 15,
        },
        {
            "id": "cr-service",
            "condition": "resourceSpans[0].resource.attributes[?key=='service.name'] | [0] != `null`",
            "target_node_type": "Service",
            "priority": 10,
        },
    ],
}
