apiVersion: v1
kind: Secret
metadata:
  name: postgres-credentials
  namespace: monitoring-demo
type: Opaque
stringData:
  POSTGRES_USER: user
  POSTGRES_PASSWORD: password
  POSTGRES_DB: db
  DATABASE_URL: postgresql://user:password@postgres-db:5432/db
