apiVersion: v1
kind: Service
metadata:
  name: beyla-metrics
  namespace: monitoring-demo
spec:
  clusterIP: None
  selector:
    app: beyla
  ports:
    - name: svc-metrics
      port: 8999
      targetPort: 8999
    - name: internal-metrics
      port: 8998
      targetPort: 8998
