from __future__ import annotations

U: dict[str, str] = {
    "api-gateway":           "urn:service:api-gateway",
    "auth-service":          "urn:service:auth-service",
    "user-service":          "urn:service:user-service",
    "cart-service":          "urn:service:cart-service",
    "order-service":         "urn:service:order-service",
    "payment-service":       "urn:service:payment-service",
    "notification-service":  "urn:service:notification-service",
    "product-service":       "urn:service:product-service",
    "inventory-service":     "urn:service:inventory-service",
    "search-service":        "urn:service:search-service",
    "recommendation-service":"urn:service:recommendation-service",

    "ep-orders-post":        "urn:endpoint:order-service:/api/v1/orders:POST",
    "ep-orders-get":         "urn:endpoint:order-service:/api/v1/orders:GET",
    "ep-payments-post":      "urn:endpoint:payment-service:/api/v1/payments:POST",
    "ep-products-get":       "urn:endpoint:product-service:/api/v1/products:GET",
    "ep-cart-post":          "urn:endpoint:cart-service:/api/v1/cart:POST",
    "ep-search-get":         "urn:endpoint:search-service:/api/v1/search:GET",
    "ep-auth-login":         "urn:endpoint:auth-service:/api/v1/auth/login:POST",
    "ep-user-profile":       "urn:endpoint:user-service:/api/v1/users/me:GET",

    "dep-api-gw":            "urn:k8s:deployment:prod:api-gateway",
    "dep-auth":              "urn:k8s:deployment:prod:auth-service",
    "dep-user":              "urn:k8s:deployment:prod:user-service",
    "dep-cart":              "urn:k8s:deployment:prod:cart-service",
    "dep-order":             "urn:k8s:deployment:prod:order-service",
    "dep-payment":           "urn:k8s:deployment:prod:payment-service",
    "dep-notification":      "urn:k8s:deployment:prod:notification-service",
    "dep-product":           "urn:k8s:deployment:prod:product-service",
    "dep-inventory":         "urn:k8s:deployment:prod:inventory-service",
    "dep-search":            "urn:k8s:deployment:prod:search-service",
    "dep-recommendation":    "urn:k8s:deployment:prod:recommendation-service",

    "pod-api-gw-0":          "urn:k8s:pod:prod:api-gateway-7d8f5c-xk2n4",
    "pod-api-gw-1":          "urn:k8s:pod:prod:api-gateway-7d8f5c-m3j7p",
    "pod-api-gw-2":          "urn:k8s:pod:prod:api-gateway-7d8f5c-r9q1w",
    "pod-auth-0":            "urn:k8s:pod:prod:auth-service-4a2b1c-h8k3m",
    "pod-auth-1":            "urn:k8s:pod:prod:auth-service-4a2b1c-p5n9v",
    "pod-user-0":            "urn:k8s:pod:prod:user-service-6e3d9f-t2w8x",
    "pod-cart-0":            "urn:k8s:pod:prod:cart-service-2c7a4b-y6z1q",
    "pod-cart-1":            "urn:k8s:pod:prod:cart-service-2c7a4b-d4f8s",
    "pod-order-0":           "urn:k8s:pod:prod:order-service-8b5e2d-j3l7n",
    "pod-order-1":           "urn:k8s:pod:prod:order-service-8b5e2d-a1c5g",
    "pod-payment-0":         "urn:k8s:pod:prod:payment-service-1f9c3a-w7y2t",
    "pod-payment-1":         "urn:k8s:pod:prod:payment-service-1f9c3a-e4h8k",
    "pod-notification-0":    "urn:k8s:pod:prod:notification-svc-3d6b8e-m2p6r",
    "pod-product-0":         "urn:k8s:pod:prod:product-service-5a1c7d-v9x3z",
    "pod-product-1":         "urn:k8s:pod:prod:product-service-5a1c7d-b6f2j",
    "pod-inventory-0":       "urn:k8s:pod:prod:inventory-svc-9e4f2a-s8u1w",
    "pod-search-0":          "urn:k8s:pod:prod:search-service-7c3d1b-k5n9q",
    "pod-recommendation-0":  "urn:k8s:pod:prod:recommendation-svc-2a8e4f-g7j3l",

    "node-1":                "urn:k8s:node:prod:ip-10-0-1-101.ec2.internal",
    "node-2":                "urn:k8s:node:prod:ip-10-0-2-102.ec2.internal",
    "node-3":                "urn:k8s:node:prod:ip-10-0-3-103.ec2.internal",
    "node-4":                "urn:k8s:node:prod:ip-10-0-1-104.ec2.internal",
    "node-5":                "urn:k8s:node:prod:ip-10-0-2-105.ec2.internal",

    "db-users":              "urn:db:postgres:users-primary.cxyz123.eu-central-1.rds.amazonaws.com",
    "db-orders":             "urn:db:postgres:orders-primary.cxyz456.eu-central-1.rds.amazonaws.com",
    "db-payment":            "urn:db:postgres:payments-primary.cxyz789.eu-central-1.rds.amazonaws.com",
    "db-inventory":          "urn:db:postgres:inventory-primary.cxyz321.eu-central-1.rds.amazonaws.com",
    "db-products":           "urn:db:mongo:products.cluster0.mongodb.net",

    "tbl-users":             "urn:table:users-db:public.users",
    "tbl-sessions":          "urn:table:users-db:public.sessions",
    "tbl-orders":            "urn:table:orders-db:public.orders",
    "tbl-order-items":       "urn:table:orders-db:public.order_items",
    "tbl-payments":          "urn:table:payment-db:public.transactions",
    "tbl-refunds":           "urn:table:payment-db:public.refunds",
    "tbl-inventory":         "urn:table:inventory-db:public.stock_levels",

    "topic-order-events":    "urn:kafka:topic:prod.orders.events",
    "topic-payment-events":  "urn:kafka:topic:prod.payments.events",
    "topic-notif-events":    "urn:kafka:topic:prod.notifications.events",
    "topic-inventory-events":"urn:kafka:topic:prod.inventory.events",

    "cache-session":         "urn:redis:cluster:session-cache.xyz.euc1.cache.amazonaws.com",
    "cache-product":         "urn:redis:cluster:product-cache.xyz.euc1.cache.amazonaws.com",
    "cache-cart":            "urn:redis:cluster:cart-cache.xyz.euc1.cache.amazonaws.com",
    "cache-rate-limit":      "urn:redis:cluster:rate-limit.xyz.euc1.cache.amazonaws.com",
    "cache-search":          "urn:redis:cluster:search-cache.xyz.euc1.cache.amazonaws.com",

    "ext-stripe":            "urn:external:stripe-api",
    "ext-sendgrid":          "urn:external:sendgrid-api",
    "ext-twilio":            "urn:external:twilio-api",
    "ext-elasticsearch":     "urn:external:elasticsearch-cloud",
    "ext-cloudflare":        "urn:external:cloudflare-cdn",

    "secret-stripe-key":     "urn:secret:vault:production/stripe-api-key",
    "secret-db-credentials": "urn:secret:vault:production/database-credentials",
    "secret-jwt-signing":    "urn:secret:vault:production/jwt-signing-key",
    "secret-sendgrid-key":   "urn:secret:vault:production/sendgrid-api-key",
    "secret-kafka-creds":    "urn:secret:vault:production/kafka-credentials",
    "config-feature-flags":  "urn:config:consul:production/feature-flags",

    "lib-grpc-go":           "urn:lib:go:google.golang.org/grpc:v1.62.0",
    "lib-sqlalchemy":        "urn:lib:python:sqlalchemy:v2.0.28",
    "lib-kafka-go":          "urn:lib:go:github.com/segmentio/kafka-go:v0.4.47",
    "lib-spring-boot":       "urn:lib:java:org.springframework.boot:v3.2.4",
    "lib-express":           "urn:lib:nodejs:express:v4.18.2",
    "lib-pydantic":          "urn:lib:python:pydantic:v2.6.4",

    "team-platform":         "urn:team:platform-engineering",
    "team-payments":         "urn:team:payments",
    "team-users":            "urn:team:identity-access",
    "team-orders":           "urn:team:order-management",
    "team-product":          "urn:team:product-catalog",
    "team-search":           "urn:team:search-discovery",

    #  SLOs 
    "slo-api-gw-avail":      "urn:slo:api-gateway:availability",
    "slo-api-gw-latency":    "urn:slo:api-gateway:latency-p99",
    "slo-payment-avail":     "urn:slo:payment-service:availability",
    "slo-payment-latency":   "urn:slo:payment-service:latency-p99",
    "slo-order-latency":     "urn:slo:order-service:latency-p99",
    "slo-search-latency":    "urn:slo:search-service:latency-p99",

    "cluster-prod":          "urn:k8s:cluster:eks:eu-central-1:prod-ecommerce",
}


STATIC_NODES: list[dict] = [
    {"id": U["api-gateway"], "type": "Service", "name": "API Gateway",
     "language": "go", "framework": "gin", "version": "2.4.1",
     "repository_url": "https://github.com/acme/api-gateway",
     "tier": 1, "is_external": False, "environment": "production",
     "memory_allocated_mb": 512, "cpu_allocated_cores": 1.0},

    {"id": U["auth-service"], "type": "Service", "name": "Auth Service",
     "language": "go", "framework": "gin", "version": "1.12.0",
     "repository_url": "https://github.com/acme/auth-service",
     "tier": 1, "is_external": False, "environment": "production",
     "memory_allocated_mb": 256, "cpu_allocated_cores": 0.5},

    {"id": U["user-service"], "type": "Service", "name": "User Service",
     "language": "python", "framework": "fastapi", "version": "3.5.2",
     "repository_url": "https://github.com/acme/user-service",
     "tier": 2, "is_external": False, "environment": "production",
     "memory_allocated_mb": 512, "cpu_allocated_cores": 0.5},

    {"id": U["cart-service"], "type": "Service", "name": "Cart Service",
     "language": "nodejs", "framework": "express", "version": "2.1.0",
     "repository_url": "https://github.com/acme/cart-service",
     "tier": 2, "is_external": False, "environment": "production",
     "memory_allocated_mb": 256, "cpu_allocated_cores": 0.25},

    {"id": U["order-service"], "type": "Service", "name": "Order Service",
     "language": "java", "framework": "spring-boot", "version": "4.2.0",
     "repository_url": "https://github.com/acme/order-service",
     "tier": 1, "is_external": False, "environment": "production",
     "memory_allocated_mb": 1024, "cpu_allocated_cores": 1.0},

    {"id": U["payment-service"], "type": "Service", "name": "Payment Service",
     "language": "java", "framework": "spring-boot", "version": "3.1.5",
     "repository_url": "https://github.com/acme/payment-service",
     "tier": 1, "is_external": False, "environment": "production",
     "memory_allocated_mb": 768, "cpu_allocated_cores": 0.75},

    {"id": U["notification-service"], "type": "Service", "name": "Notification Service",
     "language": "python", "framework": "fastapi", "version": "1.8.3",
     "repository_url": "https://github.com/acme/notification-service",
     "tier": 3, "is_external": False, "environment": "production",
     "memory_allocated_mb": 256, "cpu_allocated_cores": 0.25},

    {"id": U["product-service"], "type": "Service", "name": "Product Catalog",
     "language": "nodejs", "framework": "express", "version": "5.3.1",
     "repository_url": "https://github.com/acme/product-service",
     "tier": 2, "is_external": False, "environment": "production",
     "memory_allocated_mb": 512, "cpu_allocated_cores": 0.5},

    {"id": U["inventory-service"], "type": "Service", "name": "Inventory Service",
     "language": "go", "framework": "gin", "version": "1.4.2",
     "repository_url": "https://github.com/acme/inventory-service",
     "tier": 2, "is_external": False, "environment": "production",
     "memory_allocated_mb": 256, "cpu_allocated_cores": 0.5},

    {"id": U["search-service"], "type": "Service", "name": "Search Service",
     "language": "python", "framework": "fastapi", "version": "2.0.1",
     "repository_url": "https://github.com/acme/search-service",
     "tier": 2, "is_external": False, "environment": "production",
     "memory_allocated_mb": 512, "cpu_allocated_cores": 0.5},

    {"id": U["recommendation-service"], "type": "Service", "name": "Recommendation Engine",
     "language": "python", "framework": "fastapi", "version": "1.2.0",
     "repository_url": "https://github.com/acme/recommendation-service",
     "tier": 3, "is_external": False, "environment": "production",
     "memory_allocated_mb": 1024, "cpu_allocated_cores": 1.0},

    {"id": U["ep-orders-post"], "type": "Endpoint", "name": "POST /api/v1/orders",
     "path": "/api/v1/orders", "method": "POST", "is_public": True,
     "auth_required": True, "payload_format": "json", "timeout_ms": 5000,
     "rps_limit": 500.0, "environment": "production"},

    {"id": U["ep-orders-get"], "type": "Endpoint", "name": "GET /api/v1/orders",
     "path": "/api/v1/orders", "method": "GET", "is_public": True,
     "auth_required": True, "payload_format": "json", "timeout_ms": 3000,
     "rps_limit": 2000.0, "environment": "production"},

    {"id": U["ep-payments-post"], "type": "Endpoint", "name": "POST /api/v1/payments",
     "path": "/api/v1/payments", "method": "POST", "is_public": False,
     "auth_required": True, "payload_format": "json", "timeout_ms": 10000,
     "rps_limit": 200.0, "environment": "production"},

    {"id": U["ep-products-get"], "type": "Endpoint", "name": "GET /api/v1/products",
     "path": "/api/v1/products", "method": "GET", "is_public": True,
     "auth_required": False, "payload_format": "json", "timeout_ms": 2000,
     "rps_limit": 5000.0, "environment": "production"},

    {"id": U["ep-cart-post"], "type": "Endpoint", "name": "POST /api/v1/cart",
     "path": "/api/v1/cart", "method": "POST", "is_public": True,
     "auth_required": True, "payload_format": "json", "timeout_ms": 2000,
     "rps_limit": 3000.0, "environment": "production"},

    {"id": U["ep-search-get"], "type": "Endpoint", "name": "GET /api/v1/search",
     "path": "/api/v1/search", "method": "GET", "is_public": True,
     "auth_required": False, "payload_format": "json", "timeout_ms": 1500,
     "rps_limit": 8000.0, "environment": "production"},

    {"id": U["ep-auth-login"], "type": "Endpoint", "name": "POST /api/v1/auth/login",
     "path": "/api/v1/auth/login", "method": "POST", "is_public": True,
     "auth_required": False, "payload_format": "json", "timeout_ms": 3000,
     "rps_limit": 1000.0, "environment": "production"},

    {"id": U["ep-user-profile"], "type": "Endpoint", "name": "GET /api/v1/users/me",
     "path": "/api/v1/users/me", "method": "GET", "is_public": True,
     "auth_required": True, "payload_format": "json", "timeout_ms": 2000,
     "rps_limit": 3000.0, "environment": "production"},

    {"id": U["dep-api-gw"], "type": "Deployment", "name": "api-gateway",
     "namespace": "production", "strategy": "RollingUpdate",
     "image_tag": "acme/api-gateway:2.4.1", "environment": "production"},

    {"id": U["dep-auth"], "type": "Deployment", "name": "auth-service",
     "namespace": "production", "strategy": "RollingUpdate",
     "image_tag": "acme/auth-service:1.12.0", "environment": "production"},

    {"id": U["dep-user"], "type": "Deployment", "name": "user-service",
     "namespace": "production", "strategy": "RollingUpdate",
     "image_tag": "acme/user-service:3.5.2", "environment": "production"},

    {"id": U["dep-cart"], "type": "Deployment", "name": "cart-service",
     "namespace": "production", "strategy": "RollingUpdate",
     "image_tag": "acme/cart-service:2.1.0", "environment": "production"},

    {"id": U["dep-order"], "type": "Deployment", "name": "order-service",
     "namespace": "production", "strategy": "RollingUpdate",
     "image_tag": "acme/order-service:4.2.0", "environment": "production"},

    {"id": U["dep-payment"], "type": "Deployment", "name": "payment-service",
     "namespace": "production", "strategy": "BlueGreen",
     "image_tag": "acme/payment-service:3.1.5", "environment": "production"},

    {"id": U["dep-notification"], "type": "Deployment", "name": "notification-service",
     "namespace": "production", "strategy": "RollingUpdate",
     "image_tag": "acme/notification-service:1.8.3", "environment": "production"},

    {"id": U["dep-product"], "type": "Deployment", "name": "product-service",
     "namespace": "production", "strategy": "RollingUpdate",
     "image_tag": "acme/product-service:5.3.1", "environment": "production"},

    {"id": U["dep-inventory"], "type": "Deployment", "name": "inventory-service",
     "namespace": "production", "strategy": "RollingUpdate",
     "image_tag": "acme/inventory-service:1.4.2", "environment": "production"},

    {"id": U["dep-search"], "type": "Deployment", "name": "search-service",
     "namespace": "production", "strategy": "RollingUpdate",
     "image_tag": "acme/search-service:2.0.1", "environment": "production"},

    {"id": U["dep-recommendation"], "type": "Deployment", "name": "recommendation-service",
     "namespace": "production", "strategy": "RollingUpdate",
     "image_tag": "acme/recommendation-service:1.2.0", "environment": "production"},

    {"id": U["pod-api-gw-0"], "type": "Pod", "name": "api-gateway-7d8f5c-xk2n4",
     "namespace": "production", "phase": "Running", "environment": "production",
     "ip_address": "10.244.1.5"},
    {"id": U["pod-api-gw-1"], "type": "Pod", "name": "api-gateway-7d8f5c-m3j7p",
     "namespace": "production", "phase": "Running", "environment": "production",
     "ip_address": "10.244.2.3"},
    {"id": U["pod-api-gw-2"], "type": "Pod", "name": "api-gateway-7d8f5c-r9q1w",
     "namespace": "production", "phase": "Running", "environment": "production",
     "ip_address": "10.244.3.7"},
    {"id": U["pod-auth-0"], "type": "Pod", "name": "auth-service-4a2b1c-h8k3m",
     "namespace": "production", "phase": "Running", "environment": "production",
     "ip_address": "10.244.1.12"},
    {"id": U["pod-auth-1"], "type": "Pod", "name": "auth-service-4a2b1c-p5n9v",
     "namespace": "production", "phase": "Running", "environment": "production",
     "ip_address": "10.244.3.14"},
    {"id": U["pod-user-0"], "type": "Pod", "name": "user-service-6e3d9f-t2w8x",
     "namespace": "production", "phase": "Running", "environment": "production",
     "ip_address": "10.244.2.9"},
    {"id": U["pod-cart-0"], "type": "Pod", "name": "cart-service-2c7a4b-y6z1q",
     "namespace": "production", "phase": "Running", "environment": "production",
     "ip_address": "10.244.4.2"},
    {"id": U["pod-cart-1"], "type": "Pod", "name": "cart-service-2c7a4b-d4f8s",
     "namespace": "production", "phase": "Running", "environment": "production",
     "ip_address": "10.244.5.6"},
    {"id": U["pod-order-0"], "type": "Pod", "name": "order-service-8b5e2d-j3l7n",
     "namespace": "production", "phase": "Running", "environment": "production",
     "ip_address": "10.244.1.18"},
    {"id": U["pod-order-1"], "type": "Pod", "name": "order-service-8b5e2d-a1c5g",
     "namespace": "production", "phase": "Running", "environment": "production",
     "ip_address": "10.244.2.21"},
    {"id": U["pod-payment-0"], "type": "Pod", "name": "payment-service-1f9c3a-w7y2t",
     "namespace": "production", "phase": "Running", "environment": "production",
     "ip_address": "10.244.3.4"},
    {"id": U["pod-payment-1"], "type": "Pod", "name": "payment-service-1f9c3a-e4h8k",
     "namespace": "production", "phase": "Running", "environment": "production",
     "ip_address": "10.244.1.25"},
    {"id": U["pod-notification-0"], "type": "Pod", "name": "notification-svc-3d6b8e-m2p6r",
     "namespace": "production", "phase": "Running", "environment": "production",
     "ip_address": "10.244.4.8"},
    {"id": U["pod-product-0"], "type": "Pod", "name": "product-service-5a1c7d-v9x3z",
     "namespace": "production", "phase": "Running", "environment": "production",
     "ip_address": "10.244.2.15"},
    {"id": U["pod-product-1"], "type": "Pod", "name": "product-service-5a1c7d-b6f2j",
     "namespace": "production", "phase": "Running", "environment": "production",
     "ip_address": "10.244.5.11"},
    {"id": U["pod-inventory-0"], "type": "Pod", "name": "inventory-svc-9e4f2a-s8u1w",
     "namespace": "production", "phase": "Running", "environment": "production",
     "ip_address": "10.244.3.19"},
    {"id": U["pod-search-0"], "type": "Pod", "name": "search-service-7c3d1b-k5n9q",
     "namespace": "production", "phase": "Running", "environment": "production",
     "ip_address": "10.244.4.3"},
    {"id": U["pod-recommendation-0"], "type": "Pod", "name": "recommendation-svc-2a8e4f-g7j3l",
     "namespace": "production", "phase": "Running", "environment": "production",
     "ip_address": "10.244.5.22"},

    {"id": U["node-1"], "type": "Node", "name": "ip-10-0-1-101",
     "instance_type": "m6i.2xlarge", "architecture": "amd64",
     "capacity_cpu": 8, "capacity_memory_gb": 32.0,
     "region": "eu-central-1", "zone": "eu-central-1a",
     "os_image": "Amazon Linux 2023", "kubelet_version": "v1.29.2",
     "environment": "production"},
    {"id": U["node-2"], "type": "Node", "name": "ip-10-0-2-102",
     "instance_type": "m6i.2xlarge", "architecture": "amd64",
     "capacity_cpu": 8, "capacity_memory_gb": 32.0,
     "region": "eu-central-1", "zone": "eu-central-1b",
     "os_image": "Amazon Linux 2023", "kubelet_version": "v1.29.2",
     "environment": "production"},
    {"id": U["node-3"], "type": "Node", "name": "ip-10-0-3-103",
     "instance_type": "m6i.2xlarge", "architecture": "amd64",
     "capacity_cpu": 8, "capacity_memory_gb": 32.0,
     "region": "eu-central-1", "zone": "eu-central-1c",
     "os_image": "Amazon Linux 2023", "kubelet_version": "v1.29.2",
     "environment": "production"},
    {"id": U["node-4"], "type": "Node", "name": "ip-10-0-1-104",
     "instance_type": "c6i.xlarge", "architecture": "amd64",
     "capacity_cpu": 4, "capacity_memory_gb": 8.0,
     "region": "eu-central-1", "zone": "eu-central-1a",
     "os_image": "Amazon Linux 2023", "kubelet_version": "v1.29.2",
     "environment": "production"},
    {"id": U["node-5"], "type": "Node", "name": "ip-10-0-2-105",
     "instance_type": "c6i.xlarge", "architecture": "amd64",
     "capacity_cpu": 4, "capacity_memory_gb": 8.0,
     "region": "eu-central-1", "zone": "eu-central-1b",
     "os_image": "Amazon Linux 2023", "kubelet_version": "v1.29.2",
     "environment": "production"},

    {"id": U["db-users"], "type": "Database", "name": "Users DB",
     "engine": "postgresql", "version": "16.2", "capacity_gb": 100.0,
     "is_managed": True, "region": "eu-central-1", "instance_class": "db.r6g.large",
     "multi_az": True, "max_connections": 200, "backup_retention_days": 14,
     "environment": "production"},

    {"id": U["db-orders"], "type": "Database", "name": "Orders DB",
     "engine": "postgresql", "version": "16.2", "capacity_gb": 500.0,
     "is_managed": True, "region": "eu-central-1", "instance_class": "db.r6g.xlarge",
     "multi_az": True, "max_connections": 500, "backup_retention_days": 30,
     "environment": "production"},

    {"id": U["db-payment"], "type": "Database", "name": "Payments DB",
     "engine": "postgresql", "version": "16.2", "capacity_gb": 200.0,
     "is_managed": True, "region": "eu-central-1", "instance_class": "db.r6g.large",
     "multi_az": True, "max_connections": 300, "backup_retention_days": 90,
     "environment": "production"},

    {"id": U["db-inventory"], "type": "Database", "name": "Inventory DB",
     "engine": "postgresql", "version": "16.2", "capacity_gb": 50.0,
     "is_managed": True, "region": "eu-central-1", "instance_class": "db.r6g.medium",
     "multi_az": False, "max_connections": 100, "backup_retention_days": 7,
     "environment": "production"},

    {"id": U["db-products"], "type": "Database", "name": "Products DB",
     "engine": "mongodb", "version": "7.0.5", "capacity_gb": 250.0,
     "is_managed": True, "region": "eu-central-1",
     "multi_az": False, "max_connections": 200,
     "environment": "production"},

    {"id": U["tbl-users"], "type": "Table", "name": "public.users",
     "schema_name": "public", "primary_key": ["id"], "is_partitioned": False,
     "row_count": 2_450_000, "index_count": 4, "environment": "production"},

    {"id": U["tbl-sessions"], "type": "Table", "name": "public.sessions",
     "schema_name": "public", "primary_key": ["id"], "is_partitioned": False,
     "row_count": 180_000, "index_count": 3, "retention_days": 30,
     "environment": "production"},

    {"id": U["tbl-orders"], "type": "Table", "name": "public.orders",
     "schema_name": "public", "primary_key": ["id"], "is_partitioned": True,
     "row_count": 12_800_000, "index_count": 6, "environment": "production"},

    {"id": U["tbl-order-items"], "type": "Table", "name": "public.order_items",
     "schema_name": "public", "primary_key": ["id"], "is_partitioned": True,
     "row_count": 38_500_000, "index_count": 4, "environment": "production"},

    {"id": U["tbl-payments"], "type": "Table", "name": "public.transactions",
     "schema_name": "public", "primary_key": ["id"], "is_partitioned": True,
     "row_count": 9_200_000, "index_count": 5, "environment": "production"},

    {"id": U["tbl-refunds"], "type": "Table", "name": "public.refunds",
     "schema_name": "public", "primary_key": ["id"], "is_partitioned": False,
     "row_count": 340_000, "index_count": 3, "environment": "production"},

    {"id": U["tbl-inventory"], "type": "Table", "name": "public.stock_levels",
     "schema_name": "public", "primary_key": ["sku_id", "warehouse_id"],
     "is_partitioned": False, "row_count": 850_000, "index_count": 3,
     "environment": "production"},

    {"id": U["topic-order-events"], "type": "QueueTopic", "name": "prod.orders.events",
     "broker": "kafka", "partitions": 12, "replication_factor": 3,
     "retention_ms": 604800000, "environment": "production"},

    {"id": U["topic-payment-events"], "type": "QueueTopic", "name": "prod.payments.events",
     "broker": "kafka", "partitions": 6, "replication_factor": 3,
     "retention_ms": 604800000, "environment": "production"},

    {"id": U["topic-notif-events"], "type": "QueueTopic", "name": "prod.notifications.events",
     "broker": "kafka", "partitions": 6, "replication_factor": 3,
     "retention_ms": 86400000, "environment": "production"},

    {"id": U["topic-inventory-events"], "type": "QueueTopic", "name": "prod.inventory.events",
     "broker": "kafka", "partitions": 8, "replication_factor": 3,
     "retention_ms": 259200000, "environment": "production"},

    {"id": U["cache-session"], "type": "Cache", "name": "Session Cache",
     "engine": "redis", "eviction_policy": "allkeys-lru", "max_memory_mb": 4096,
     "environment": "production"},

    {"id": U["cache-product"], "type": "Cache", "name": "Product Cache",
     "engine": "redis", "eviction_policy": "volatile-ttl", "max_memory_mb": 8192,
     "environment": "production"},

    {"id": U["cache-cart"], "type": "Cache", "name": "Cart Cache",
     "engine": "redis", "eviction_policy": "allkeys-lru", "max_memory_mb": 2048,
     "environment": "production"},

    {"id": U["cache-rate-limit"], "type": "Cache", "name": "Rate Limit Store",
     "engine": "redis", "eviction_policy": "volatile-ttl", "max_memory_mb": 1024,
     "environment": "production"},

    {"id": U["cache-search"], "type": "Cache", "name": "Search Cache",
     "engine": "redis", "eviction_policy": "volatile-lfu", "max_memory_mb": 4096,
     "environment": "production"},

    {"id": U["ext-stripe"], "type": "ExternalAPI", "name": "Stripe API",
     "provider": "stripe", "base_url": "https://api.stripe.com/v1",
     "auth_type": "api_key", "sla_percentage": 99.99,
     "documentation_url": "https://stripe.com/docs/api"},

    {"id": U["ext-sendgrid"], "type": "ExternalAPI", "name": "SendGrid API",
     "provider": "sendgrid", "base_url": "https://api.sendgrid.com/v3",
     "auth_type": "api_key", "sla_percentage": 99.95,
     "documentation_url": "https://docs.sendgrid.com/api-reference"},

    {"id": U["ext-twilio"], "type": "ExternalAPI", "name": "Twilio API",
     "provider": "twilio", "base_url": "https://api.twilio.com/2010-04-01",
     "auth_type": "basic", "sla_percentage": 99.95,
     "documentation_url": "https://www.twilio.com/docs/usage/api"},

    {"id": U["ext-elasticsearch"], "type": "ExternalAPI", "name": "Elastic Cloud",
     "provider": "elastic", "base_url": "https://prod-search.es.eu-central-1.aws.cloud.es.io",
     "auth_type": "api_key", "sla_percentage": 99.95,
     "documentation_url": "https://www.elastic.co/guide/en/elasticsearch/reference"},

    {"id": U["ext-cloudflare"], "type": "ExternalAPI", "name": "Cloudflare CDN",
     "provider": "cloudflare", "base_url": "https://api.cloudflare.com/client/v4",
     "auth_type": "api_key", "sla_percentage": 99.99,
     "documentation_url": "https://developers.cloudflare.com/api"},

    {"id": U["secret-stripe-key"], "type": "SecretConfig", "name": "Stripe API Key",
     "provider": "hashicorp_vault", "is_encrypted": True,
     "rotation_interval_days": 90, "vault_path": "secret/production/stripe",
     "environment": "production"},

    {"id": U["secret-db-credentials"], "type": "SecretConfig", "name": "Database Credentials",
     "provider": "hashicorp_vault", "is_encrypted": True,
     "rotation_interval_days": 30, "vault_path": "secret/production/databases",
     "environment": "production"},

    {"id": U["secret-jwt-signing"], "type": "SecretConfig", "name": "JWT Signing Key",
     "provider": "hashicorp_vault", "is_encrypted": True,
     "rotation_interval_days": 7, "vault_path": "secret/production/jwt",
     "algorithm": "RS256", "environment": "production"},

    {"id": U["secret-sendgrid-key"], "type": "SecretConfig", "name": "SendGrid API Key",
     "provider": "hashicorp_vault", "is_encrypted": True,
     "rotation_interval_days": 180, "vault_path": "secret/production/sendgrid",
     "environment": "production"},

    {"id": U["secret-kafka-creds"], "type": "SecretConfig", "name": "Kafka SASL Credentials",
     "provider": "hashicorp_vault", "is_encrypted": True,
     "rotation_interval_days": 60, "vault_path": "secret/production/kafka",
     "environment": "production"},

    {"id": U["config-feature-flags"], "type": "SecretConfig", "name": "Feature Flags",
     "provider": "consul", "is_encrypted": False,
     "vault_path": "config/production/feature-flags",
     "environment": "production"},

    {"id": U["lib-grpc-go"], "type": "Library", "name": "gRPC (Go)",
     "package_manager": "gomod", "version": "1.62.0", "license": "Apache-2.0",
     "cve_count": 0, "is_internal": False},

    {"id": U["lib-sqlalchemy"], "type": "Library", "name": "SQLAlchemy",
     "package_manager": "pip", "version": "2.0.28", "license": "MIT",
     "cve_count": 0, "is_internal": False},

    {"id": U["lib-kafka-go"], "type": "Library", "name": "kafka-go",
     "package_manager": "gomod", "version": "0.4.47", "license": "MIT",
     "cve_count": 0, "is_internal": False},

    {"id": U["lib-spring-boot"], "type": "Library", "name": "Spring Boot",
     "package_manager": "maven", "version": "3.2.4", "license": "Apache-2.0",
     "cve_count": 1, "is_internal": False},

    {"id": U["lib-express"], "type": "Library", "name": "Express.js",
     "package_manager": "npm", "version": "4.18.2", "license": "MIT",
     "cve_count": 0, "is_internal": False},

    {"id": U["lib-pydantic"], "type": "Library", "name": "Pydantic",
     "package_manager": "pip", "version": "2.6.4", "license": "MIT",
     "cve_count": 0, "is_internal": False},

    {"id": U["team-platform"], "type": "TeamOwner", "name": "Platform Engineering",
     "email": "platform@acme.io", "slack_channel": "#team-platform",
     "pagerduty_service": "P0PLAT", "lead_name": "Alice Chen",
     "department": "Engineering", "cost_center": "CC-ENG-001"},

    {"id": U["team-payments"], "type": "TeamOwner", "name": "Payments Team",
     "email": "payments@acme.io", "slack_channel": "#team-payments",
     "pagerduty_service": "P0PAY", "lead_name": "Bob Martinez",
     "department": "Engineering", "cost_center": "CC-ENG-002"},

    {"id": U["team-users"], "type": "TeamOwner", "name": "Identity & Access",
     "email": "identity@acme.io", "slack_channel": "#team-identity",
     "pagerduty_service": "P0IAM", "lead_name": "Carol Singh",
     "department": "Engineering", "cost_center": "CC-ENG-003"},

    {"id": U["team-orders"], "type": "TeamOwner", "name": "Order Management",
     "email": "orders@acme.io", "slack_channel": "#team-orders",
     "pagerduty_service": "P0ORD", "lead_name": "David Kim",
     "department": "Engineering", "cost_center": "CC-ENG-004"},

    {"id": U["team-product"], "type": "TeamOwner", "name": "Product Catalog",
     "email": "catalog@acme.io", "slack_channel": "#team-catalog",
     "pagerduty_service": "P0CAT", "lead_name": "Eva Müller",
     "department": "Engineering", "cost_center": "CC-ENG-005"},

    {"id": U["team-search"], "type": "TeamOwner", "name": "Search & Discovery",
     "email": "search@acme.io", "slack_channel": "#team-search",
     "pagerduty_service": "P0SRC", "lead_name": "Frank Liu",
     "department": "Engineering", "cost_center": "CC-ENG-006"},

    {"id": U["slo-api-gw-avail"], "type": "SLASLO", "name": "API Gateway  Availability",
     "metric_name": "availability", "target_percentage": 99.95, "window_days": 30,
     "environment": "production"},

    {"id": U["slo-api-gw-latency"], "type": "SLASLO", "name": "API Gateway  Latency P99",
     "metric_name": "latency_p99", "target_percentage": 200.0, "window_days": 7,
     "environment": "production"},

    {"id": U["slo-payment-avail"], "type": "SLASLO", "name": "Payment Service  Availability",
     "metric_name": "availability", "target_percentage": 99.99, "window_days": 30,
     "environment": "production"},

    {"id": U["slo-payment-latency"], "type": "SLASLO", "name": "Payment Service  Latency P99",
     "metric_name": "latency_p99", "target_percentage": 500.0, "window_days": 7,
     "environment": "production"},

    {"id": U["slo-order-latency"], "type": "SLASLO", "name": "Order Service  Latency P99",
     "metric_name": "latency_p99", "target_percentage": 300.0, "window_days": 7,
     "environment": "production"},

    {"id": U["slo-search-latency"], "type": "SLASLO", "name": "Search  Latency P99",
     "metric_name": "latency_p99", "target_percentage": 150.0, "window_days": 7,
     "environment": "production"},

    {"id": U["cluster-prod"], "type": "RegionCluster", "name": "prod-ecommerce",
     "provider": "aws", "region_code": "eu-central-1",
     "zones": ["eu-central-1a", "eu-central-1b", "eu-central-1c"],
     "k8s_version": "1.29.2", "node_count": 5, "is_active": True,
     "vpc_id": "vpc-0a1b2c3d4e5f6g7h8",
     "total_cpu": 32, "total_memory_gb": 112.0,
     "environment": "production"},
]


STATIC_EDGES: list[dict] = [
    {"source_id": U["api-gateway"],         "target_id": U["auth-service"],           "type": "calls"},
    {"source_id": U["api-gateway"],         "target_id": U["user-service"],           "type": "calls"},
    {"source_id": U["api-gateway"],         "target_id": U["cart-service"],           "type": "calls"},
    {"source_id": U["api-gateway"],         "target_id": U["order-service"],          "type": "calls"},
    {"source_id": U["api-gateway"],         "target_id": U["product-service"],        "type": "calls"},
    {"source_id": U["api-gateway"],         "target_id": U["search-service"],         "type": "calls"},
    {"source_id": U["order-service"],       "target_id": U["payment-service"],        "type": "calls"},
    {"source_id": U["order-service"],       "target_id": U["inventory-service"],      "type": "calls"},
    {"source_id": U["order-service"],       "target_id": U["notification-service"],   "type": "calls"},
    {"source_id": U["cart-service"],        "target_id": U["product-service"],        "type": "calls"},
    {"source_id": U["cart-service"],        "target_id": U["inventory-service"],      "type": "calls"},
    {"source_id": U["payment-service"],     "target_id": U["ext-stripe"],             "type": "calls"},
    {"source_id": U["notification-service"],"target_id": U["ext-sendgrid"],           "type": "calls"},
    {"source_id": U["notification-service"],"target_id": U["ext-twilio"],             "type": "calls"},
    {"source_id": U["search-service"],      "target_id": U["ext-elasticsearch"],      "type": "calls"},
    {"source_id": U["product-service"],     "target_id": U["recommendation-service"], "type": "calls"},
    {"source_id": U["api-gateway"],         "target_id": U["ext-cloudflare"],         "type": "calls"},

    {"source_id": U["order-service"],       "target_id": U["topic-order-events"],     "type": "publishesto"},
    {"source_id": U["payment-service"],     "target_id": U["topic-payment-events"],   "type": "publishesto"},
    {"source_id": U["notification-service"],"target_id": U["topic-notif-events"],     "type": "publishesto"},
    {"source_id": U["inventory-service"],   "target_id": U["topic-inventory-events"], "type": "publishesto"},
    {"source_id": U["cart-service"],        "target_id": U["topic-order-events"],     "type": "publishesto"},

    #  Kafka consume (6) 
    {"source_id": U["notification-service"],"target_id": U["topic-order-events"],     "type": "consumesfrom"},
    {"source_id": U["notification-service"],"target_id": U["topic-payment-events"],   "type": "consumesfrom"},
    {"source_id": U["inventory-service"],   "target_id": U["topic-order-events"],     "type": "consumesfrom"},
    {"source_id": U["payment-service"],     "target_id": U["topic-order-events"],     "type": "consumesfrom"},
    {"source_id": U["order-service"],       "target_id": U["topic-payment-events"],   "type": "consumesfrom"},
    {"source_id": U["recommendation-service"],"target_id": U["topic-order-events"],   "type": "consumesfrom"},

    {"source_id": U["user-service"],       "target_id": U["db-users"],      "type": "reads"},
    {"source_id": U["auth-service"],       "target_id": U["db-users"],      "type": "reads"},
    {"source_id": U["order-service"],      "target_id": U["db-orders"],     "type": "reads"},
    {"source_id": U["payment-service"],    "target_id": U["db-payment"],    "type": "reads"},
    {"source_id": U["product-service"],    "target_id": U["db-products"],   "type": "reads"},
    {"source_id": U["inventory-service"],  "target_id": U["db-inventory"],  "type": "reads"},
    {"source_id": U["search-service"],     "target_id": U["db-products"],   "type": "reads"},
    {"source_id": U["recommendation-service"],"target_id": U["db-orders"],  "type": "reads"},

    {"source_id": U["user-service"],       "target_id": U["tbl-users"],      "type": "writes"},
    {"source_id": U["auth-service"],       "target_id": U["tbl-sessions"],   "type": "writes"},
    {"source_id": U["order-service"],      "target_id": U["tbl-orders"],     "type": "writes"},
    {"source_id": U["order-service"],      "target_id": U["tbl-order-items"],"type": "writes"},
    {"source_id": U["payment-service"],    "target_id": U["tbl-payments"],   "type": "writes"},
    {"source_id": U["payment-service"],    "target_id": U["tbl-refunds"],    "type": "writes"},
    {"source_id": U["product-service"],    "target_id": U["db-products"],    "type": "writes"},
    {"source_id": U["inventory-service"],  "target_id": U["tbl-inventory"],  "type": "writes"},
    {"source_id": U["user-service"],       "target_id": U["tbl-sessions"],   "type": "writes"},

    #  Cache reads (7) 
    {"source_id": U["auth-service"],       "target_id": U["cache-session"],   "type": "reads"},
    {"source_id": U["user-service"],       "target_id": U["cache-session"],   "type": "reads"},
    {"source_id": U["product-service"],    "target_id": U["cache-product"],   "type": "reads"},
    {"source_id": U["cart-service"],       "target_id": U["cache-cart"],      "type": "reads"},
    {"source_id": U["api-gateway"],        "target_id": U["cache-rate-limit"],"type": "reads"},
    {"source_id": U["search-service"],     "target_id": U["cache-search"],    "type": "reads"},
    {"source_id": U["recommendation-service"],"target_id": U["cache-product"],"type": "reads"},

    {"source_id": U["auth-service"],       "target_id": U["cache-session"],   "type": "writes"},
    {"source_id": U["product-service"],    "target_id": U["cache-product"],   "type": "writes"},
    {"source_id": U["cart-service"],       "target_id": U["cache-cart"],      "type": "writes"},
    {"source_id": U["api-gateway"],        "target_id": U["cache-rate-limit"],"type": "writes"},
    {"source_id": U["search-service"],     "target_id": U["cache-search"],    "type": "writes"},
    {"source_id": U["user-service"],       "target_id": U["cache-session"],   "type": "writes"},

    {"source_id": U["api-gateway"],            "target_id": U["dep-api-gw"],        "type": "deployedon"},
    {"source_id": U["auth-service"],           "target_id": U["dep-auth"],          "type": "deployedon"},
    {"source_id": U["user-service"],           "target_id": U["dep-user"],          "type": "deployedon"},
    {"source_id": U["cart-service"],           "target_id": U["dep-cart"],          "type": "deployedon"},
    {"source_id": U["order-service"],          "target_id": U["dep-order"],         "type": "deployedon"},
    {"source_id": U["payment-service"],        "target_id": U["dep-payment"],       "type": "deployedon"},
    {"source_id": U["notification-service"],   "target_id": U["dep-notification"],  "type": "deployedon"},
    {"source_id": U["product-service"],        "target_id": U["dep-product"],       "type": "deployedon"},
    {"source_id": U["inventory-service"],      "target_id": U["dep-inventory"],     "type": "deployedon"},
    {"source_id": U["search-service"],         "target_id": U["dep-search"],        "type": "deployedon"},
    {"source_id": U["recommendation-service"], "target_id": U["dep-recommendation"],"type": "deployedon"},

    {"source_id": U["dep-api-gw"],        "target_id": U["cluster-prod"], "type": "deployedon"},
    {"source_id": U["dep-auth"],          "target_id": U["cluster-prod"], "type": "deployedon"},
    {"source_id": U["dep-user"],          "target_id": U["cluster-prod"], "type": "deployedon"},
    {"source_id": U["dep-cart"],          "target_id": U["cluster-prod"], "type": "deployedon"},
    {"source_id": U["dep-order"],         "target_id": U["cluster-prod"], "type": "deployedon"},
    {"source_id": U["dep-payment"],       "target_id": U["cluster-prod"], "type": "deployedon"},
    {"source_id": U["dep-notification"],  "target_id": U["cluster-prod"], "type": "deployedon"},
    {"source_id": U["dep-product"],       "target_id": U["cluster-prod"], "type": "deployedon"},
    {"source_id": U["dep-inventory"],     "target_id": U["cluster-prod"], "type": "deployedon"},
    {"source_id": U["dep-search"],        "target_id": U["cluster-prod"], "type": "deployedon"},
    {"source_id": U["dep-recommendation"],"target_id": U["cluster-prod"], "type": "deployedon"},


    {"source_id": U["pod-api-gw-0"],        "target_id": U["node-1"], "type": "deployedon"},
    {"source_id": U["pod-api-gw-1"],        "target_id": U["node-2"], "type": "deployedon"},
    {"source_id": U["pod-api-gw-2"],        "target_id": U["node-3"], "type": "deployedon"},
    {"source_id": U["pod-auth-0"],          "target_id": U["node-1"], "type": "deployedon"},
    {"source_id": U["pod-auth-1"],          "target_id": U["node-3"], "type": "deployedon"},
    {"source_id": U["pod-user-0"],          "target_id": U["node-2"], "type": "deployedon"},
    {"source_id": U["pod-cart-0"],          "target_id": U["node-4"], "type": "deployedon"},
    {"source_id": U["pod-cart-1"],          "target_id": U["node-5"], "type": "deployedon"},
    {"source_id": U["pod-order-0"],         "target_id": U["node-1"], "type": "deployedon"},
    {"source_id": U["pod-order-1"],         "target_id": U["node-2"], "type": "deployedon"},
    {"source_id": U["pod-payment-0"],       "target_id": U["node-3"], "type": "deployedon"},
    {"source_id": U["pod-payment-1"],       "target_id": U["node-1"], "type": "deployedon"},
    {"source_id": U["pod-notification-0"],  "target_id": U["node-4"], "type": "deployedon"},
    {"source_id": U["pod-product-0"],       "target_id": U["node-2"], "type": "deployedon"},
    {"source_id": U["pod-product-1"],       "target_id": U["node-5"], "type": "deployedon"},
    {"source_id": U["pod-inventory-0"],     "target_id": U["node-3"], "type": "deployedon"},
    {"source_id": U["pod-search-0"],        "target_id": U["node-4"], "type": "deployedon"},
    {"source_id": U["pod-recommendation-0"],"target_id": U["node-5"], "type": "deployedon"},

    {"source_id": U["pod-api-gw-0"],        "target_id": U["dep-api-gw"],        "type": "deployedon"},
    {"source_id": U["pod-api-gw-1"],        "target_id": U["dep-api-gw"],        "type": "deployedon"},
    {"source_id": U["pod-api-gw-2"],        "target_id": U["dep-api-gw"],        "type": "deployedon"},
    {"source_id": U["pod-auth-0"],          "target_id": U["dep-auth"],          "type": "deployedon"},
    {"source_id": U["pod-auth-1"],          "target_id": U["dep-auth"],          "type": "deployedon"},
    {"source_id": U["pod-user-0"],          "target_id": U["dep-user"],          "type": "deployedon"},
    {"source_id": U["pod-cart-0"],          "target_id": U["dep-cart"],          "type": "deployedon"},
    {"source_id": U["pod-cart-1"],          "target_id": U["dep-cart"],          "type": "deployedon"},
    {"source_id": U["pod-order-0"],         "target_id": U["dep-order"],         "type": "deployedon"},
    {"source_id": U["pod-order-1"],         "target_id": U["dep-order"],         "type": "deployedon"},
    {"source_id": U["pod-payment-0"],       "target_id": U["dep-payment"],       "type": "deployedon"},
    {"source_id": U["pod-payment-1"],       "target_id": U["dep-payment"],       "type": "deployedon"},
    {"source_id": U["pod-notification-0"],  "target_id": U["dep-notification"],  "type": "deployedon"},
    {"source_id": U["pod-product-0"],       "target_id": U["dep-product"],       "type": "deployedon"},
    {"source_id": U["pod-product-1"],       "target_id": U["dep-product"],       "type": "deployedon"},
    {"source_id": U["pod-inventory-0"],     "target_id": U["dep-inventory"],     "type": "deployedon"},
    {"source_id": U["pod-search-0"],        "target_id": U["dep-search"],        "type": "deployedon"},
    {"source_id": U["pod-recommendation-0"],"target_id": U["dep-recommendation"],"type": "deployedon"},

    {"source_id": U["api-gateway"],            "target_id": U["team-platform"],  "type": "ownedby"},
    {"source_id": U["cluster-prod"],           "target_id": U["team-platform"],  "type": "ownedby"},
    {"source_id": U["auth-service"],           "target_id": U["team-users"],     "type": "ownedby"},
    {"source_id": U["user-service"],           "target_id": U["team-users"],     "type": "ownedby"},
    {"source_id": U["db-users"],               "target_id": U["team-users"],     "type": "ownedby"},
    {"source_id": U["cart-service"],           "target_id": U["team-orders"],    "type": "ownedby"},
    {"source_id": U["order-service"],          "target_id": U["team-orders"],    "type": "ownedby"},
    {"source_id": U["inventory-service"],      "target_id": U["team-orders"],    "type": "ownedby"},
    {"source_id": U["db-orders"],              "target_id": U["team-orders"],    "type": "ownedby"},
    {"source_id": U["db-inventory"],           "target_id": U["team-orders"],    "type": "ownedby"},
    {"source_id": U["payment-service"],        "target_id": U["team-payments"],  "type": "ownedby"},
    {"source_id": U["db-payment"],             "target_id": U["team-payments"],  "type": "ownedby"},
    {"source_id": U["product-service"],        "target_id": U["team-product"],   "type": "ownedby"},
    {"source_id": U["db-products"],            "target_id": U["team-product"],   "type": "ownedby"},
    {"source_id": U["search-service"],         "target_id": U["team-search"],    "type": "ownedby"},
    {"source_id": U["recommendation-service"], "target_id": U["team-search"],    "type": "ownedby"},

    {"source_id": U["api-gateway"],       "target_id": U["secret-jwt-signing"],    "type": "authenticatesvia"},
    {"source_id": U["auth-service"],      "target_id": U["secret-jwt-signing"],    "type": "authenticatesvia"},
    {"source_id": U["payment-service"],   "target_id": U["secret-stripe-key"],     "type": "authenticatesvia"},
    {"source_id": U["notification-service"],"target_id": U["secret-sendgrid-key"], "type": "authenticatesvia"},
    {"source_id": U["user-service"],      "target_id": U["secret-db-credentials"], "type": "authenticatesvia"},
    {"source_id": U["order-service"],     "target_id": U["secret-db-credentials"], "type": "authenticatesvia"},
    {"source_id": U["payment-service"],   "target_id": U["secret-db-credentials"], "type": "authenticatesvia"},
    {"source_id": U["order-service"],     "target_id": U["secret-kafka-creds"],    "type": "authenticatesvia"},

    {"source_id": U["order-service"],      "target_id": U["payment-service"],   "type": "dependson"},
    {"source_id": U["order-service"],      "target_id": U["inventory-service"], "type": "dependson"},
    {"source_id": U["api-gateway"],        "target_id": U["auth-service"],      "type": "dependson"},
    {"source_id": U["cart-service"],       "target_id": U["product-service"],   "type": "dependson"},
    {"source_id": U["user-service"],       "target_id": U["lib-sqlalchemy"],    "type": "dependson"},
    {"source_id": U["user-service"],       "target_id": U["lib-pydantic"],      "type": "dependson"},
    {"source_id": U["api-gateway"],        "target_id": U["lib-grpc-go"],       "type": "dependson"},
    {"source_id": U["order-service"],      "target_id": U["lib-spring-boot"],   "type": "dependson"},
    {"source_id": U["order-service"],      "target_id": U["lib-kafka-go"],      "type": "dependson"},
    {"source_id": U["product-service"],    "target_id": U["lib-express"],       "type": "dependson"},
    {"source_id": U["search-service"],     "target_id": U["lib-pydantic"],      "type": "dependson"},
    {"source_id": U["notification-service"],"target_id": U["lib-pydantic"],     "type": "dependson"},

    {"source_id": U["api-gateway"],     "target_id": U["slo-api-gw-avail"],    "type": "dependson"},
    {"source_id": U["api-gateway"],     "target_id": U["slo-api-gw-latency"],  "type": "dependson"},
    {"source_id": U["payment-service"], "target_id": U["slo-payment-avail"],   "type": "dependson"},
    {"source_id": U["payment-service"], "target_id": U["slo-payment-latency"], "type": "dependson"},
    {"source_id": U["order-service"],   "target_id": U["slo-order-latency"],   "type": "dependson"},
    {"source_id": U["search-service"],  "target_id": U["slo-search-latency"],  "type": "dependson"},

    {"source_id": U["ep-auth-login"],    "target_id": U["auth-service"],    "type": "ownedby"},
    {"source_id": U["ep-user-profile"],  "target_id": U["user-service"],    "type": "ownedby"},
    {"source_id": U["ep-orders-post"],   "target_id": U["order-service"],   "type": "ownedby"},
    {"source_id": U["ep-orders-get"],    "target_id": U["order-service"],   "type": "ownedby"},
    {"source_id": U["ep-payments-post"], "target_id": U["payment-service"], "type": "ownedby"},
    {"source_id": U["ep-products-get"],  "target_id": U["product-service"], "type": "ownedby"},
    {"source_id": U["ep-cart-post"],     "target_id": U["cart-service"],    "type": "ownedby"},
    {"source_id": U["ep-search-get"],    "target_id": U["search-service"],  "type": "ownedby"},

    {"source_id": U["api-gateway"],   "target_id": U["ep-auth-login"],    "type": "calls"},
    {"source_id": U["api-gateway"],   "target_id": U["ep-user-profile"],  "type": "calls"},
    {"source_id": U["api-gateway"],   "target_id": U["ep-products-get"],  "type": "calls"},
    {"source_id": U["api-gateway"],   "target_id": U["ep-cart-post"],     "type": "calls"},
    {"source_id": U["api-gateway"],   "target_id": U["ep-orders-post"],   "type": "calls"},
    {"source_id": U["api-gateway"],   "target_id": U["ep-orders-get"],    "type": "calls"},
    {"source_id": U["api-gateway"],   "target_id": U["ep-search-get"],    "type": "calls"},
    {"source_id": U["order-service"], "target_id": U["ep-payments-post"], "type": "calls"},

    {"source_id": U["node-1"], "target_id": U["cluster-prod"], "type": "deployedon"},
    {"source_id": U["node-2"], "target_id": U["cluster-prod"], "type": "deployedon"},
    {"source_id": U["node-3"], "target_id": U["cluster-prod"], "type": "deployedon"},
    {"source_id": U["node-4"], "target_id": U["cluster-prod"], "type": "deployedon"},
    {"source_id": U["node-5"], "target_id": U["cluster-prod"], "type": "deployedon"},

    {"source_id": U["api-gateway"],             "target_id": U["config-feature-flags"], "type": "dependson"},
    {"source_id": U["product-service"],         "target_id": U["config-feature-flags"], "type": "dependson"},
    {"source_id": U["recommendation-service"],  "target_id": U["config-feature-flags"], "type": "dependson"},

    {"source_id": U["api-gateway"],          "target_id": U["cache-rate-limit"], "type": "ratelimitedby"},
    {"source_id": U["payment-service"],      "target_id": U["ext-stripe"],       "type": "ratelimitedby"},
    {"source_id": U["notification-service"], "target_id": U["ext-sendgrid"],     "type": "ratelimitedby"},

    {"source_id": U["ext-sendgrid"],   "target_id": U["ext-twilio"],       "type": "fails_over_to"},
    {"source_id": U["cache-session"],  "target_id": U["db-users"],         "type": "fails_over_to"},
    {"source_id": U["cache-product"],  "target_id": U["db-products"],      "type": "fails_over_to"},
    {"source_id": U["search-service"], "target_id": U["product-service"],  "type": "fails_over_to"},
]