apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: tempo-data
  namespace: monitoring-demo
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: local-path
  resources:
    requests:
      storage: 2Gi
