apiVersion: v1
kind: ConfigMap
metadata:
  name: jaeger-ui-config
  namespace: monitoring-demo
data:
  jaeger-ui.json: |
    {
      "monitor": {
        "menuEnabled": false
      },
      "dependencies": {
        "menuEnabled": false
      }
    }
